### ISSUE TITLE
QDialog Error 

### ISSUE THREAD

**Issue by slipperybrains** [chags1313/AnnoTS#6]
(base)MacBook-Air-2 GUI % python main.py
Traceback (most recent call last):
  File "/Users/Desktop/QualAI-Signal-main 2/GUI/main.py", line 12, in <module>
    class ChecklistDialog(QtGui.QDialog):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QDialog'

**Comment by chags1313** [comment]
ChecklistDialog class now imports from QtWidgets.Qdialog. This should resolve the error.
